# Generated by Django 6.0 on 2026-04-12 05:59

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('HBL', 'Habib Bank Limited'), ('UBL', 'United Bank Limited'), ('MCB', 'Muslim Commercial Bank'), ('ABL', 'Allied Bank Limited'), ('NBP', 'National Bank of Pakistan'), ('BAF', 'Bank Alfalah'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('SADAPAY', 'Sadapay'), ('NAYAPAY', 'Nayapay'), ('Others', 'Others')], max_length=20)),
                ('account_title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, help_text='Optional IBAN number', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(help_text='Transaction ID / Reference Number', max_length=255)),
                ('payment_proof', cloudinary.models.CloudinaryField(help_text='Upload screenshot of payment', max_length=255, verbose_name='payment_proof')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.bankaccount')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.productplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
