# Generated by Django 6.0 on 2026-04-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bankaccount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[('HBL', 'Habib Bank Limited'), ('UBL', 'United Bank Limited'), ('ABL', 'Allied Bank Limited'), ('NBP', 'National Bank of Pakistan'), ('BAF', 'Bank Alfalah'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash'), ('SADAPAY', 'Sadapay'), ('NAYAPAY', 'Nayapay'), ('Binance', 'Binance'), ('Others', 'Others')], max_length=20),
        ),
    ]
